---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: tomcat-alpine-3.6
    image: alpine:3.6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-3.6
verifier:
  name: goss
  lint:
    name: yamllint
