---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: tomcat-alpine-3.7
    image: alpine:3.7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-3.7
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
