---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: tomcat-alpine-edge
    image: alpine:edge
    pre_build_image: yes
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
scenario:
  name: alpine-edge
