---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: tomcat-alpine-edge
    image: alpine:edge
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-edge
verifier:
  name: goss
  lint:
    name: yamllint
